"""add profile picture to users

Revision ID: 70612fd60c98
Revises: 17e782e83f49
Create Date: 2018-10-15 01:13:52.185430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70612fd60c98'
down_revision = '17e782e83f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
