"""Create follower requests

Revision ID: ab5891a51eaf
Revises: b0239ba527b8
Create Date: 2018-11-27 12:02:49.365364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5891a51eaf'
down_revision = 'b0239ba527b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idol_id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['idol_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follower_requests_fan_id'), 'follower_requests', ['fan_id'], unique=False)
    op.create_index(op.f('ix_follower_requests_idol_id'), 'follower_requests', ['idol_id'], unique=False)
    op.create_index('ix_unique_idol_fan_request', 'follower_requests', ['idol_id', 'fan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_idol_fan_request', table_name='follower_requests')
    op.drop_index(op.f('ix_follower_requests_idol_id'), table_name='follower_requests')
    op.drop_index(op.f('ix_follower_requests_fan_id'), table_name='follower_requests')
    op.drop_table('follower_requests')
    # ### end Alembic commands ###
