"""Create followings

Revision ID: b0239ba527b8
Revises: 292dda9f9178
Create Date: 2018-11-27 01:37:34.495236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0239ba527b8'
down_revision = '292dda9f9178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followings',
    sa.Column('idol_id', sa.Integer(), nullable=True),
    sa.Column('fan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['idol_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_followings_fan_id'), 'followings', ['fan_id'], unique=False)
    op.create_index(op.f('ix_followings_idol_id'), 'followings', ['idol_id'], unique=False)
    op.create_index('ix_unique_idol_fan', 'followings', ['idol_id', 'fan_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_idol_fan', table_name='followings')
    op.drop_index(op.f('ix_followings_idol_id'), table_name='followings')
    op.drop_index(op.f('ix_followings_fan_id'), table_name='followings')
    op.drop_table('followings')
    # ### end Alembic commands ###
