"""Create user followings

Revision ID: d81bc3368e0e
Revises: 292dda9f9178
Create Date: 2018-11-27 17:52:10.723744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81bc3368e0e'
down_revision = '292dda9f9178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_followings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idol_id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['fan_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['idol_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unique_idol_fan', 'user_followings', ['idol_id', 'fan_id'], unique=True)
    op.create_index(op.f('ix_user_followings_approved'), 'user_followings', ['approved'], unique=False)
    op.create_index(op.f('ix_user_followings_fan_id'), 'user_followings', ['fan_id'], unique=False)
    op.create_index(op.f('ix_user_followings_idol_id'), 'user_followings', ['idol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_followings_idol_id'), table_name='user_followings')
    op.drop_index(op.f('ix_user_followings_fan_id'), table_name='user_followings')
    op.drop_index(op.f('ix_user_followings_approved'), table_name='user_followings')
    op.drop_index('ix_unique_idol_fan', table_name='user_followings')
    op.drop_table('user_followings')
    # ### end Alembic commands ###
